### PR TITLE
Remove missing package 'its' from Suggests

### PR DESCRIPTION
**Pull request by mbeigel**
Package 'its' has been removed from CRAN (https://cran.r-project.org/web/packages/its/index.html) and it's inclusion in package Suggests is breaking some installation scripts such as install2.r

### CODE REVIEW

**Comment by joshuaulrich** [comment]
I'm aware of the need to remove "its".  It's not as simple as removing it from the DESCRIPTION file, which causes xts to fail CRAN checks.

**Comment by mbeigel** [comment]
I just had a chance to peruse the source code, and it looks like the only references to `its` are in `R/its.R` and `inst/unitTests/runit.its.R`. I'm assuming if I redo the functions in `R/its.R` that would be acceptable?

**Comment by joshuaulrich** [comment]
I don't know if that's all that needs to be done.  The only way I know how to check is to build the package with R-devel, then run `R CMD check --as-cran` on the tarball.  All errors, warnings, and notes must be addressed.

Even if it passes `R CMD check`, there still might be details in the documentation and/or vignettes that needs to updated to reflect the removal of the `its` package.

If you continue to make changes, please use `git commit --amend` to amend your commit, and then force-push it using `git push origin <your branch name> --force`.  I would prefer not to have multiple commits to "remove its".

**Comment by mbeigel** [comment]
Thanks for the advice and apologies about the inconvenience. I went through the source code, unit tests and documentation and removed any reference to `its` I could find. As of this commit, `R CMD check --as-cran` returns no errors of warnings, and my log is included here [check.txt](https://github.com/joshuaulrich/xts/files/789192/check.txt).

**Comment by joshuaulrich** [comment]
This looks a lot better, thanks!  There are probably some things in the vignettes that need to be addressed, but I'll take care of those.

A couple things:
1) It looks like whatever editor you used automatically removed trailing whitespace.  I understand that preference, but I prefer not including whitespace-only changes.  Can you please revert the whitespace changes?
2) When you amend the commit, can you also amend the commit message?  The change is no longer "remove from suggests".  A sentence like, "Remove all usage of 'its' package." would be fine.  And it would help future me if you replaced "missing" with "archived" in the message title.  Future me might not remember what "missing" meant in this case. ;)

**Comment by mbeigel** [comment]
Fixed the white space changes and amended the commit. I also checked for references to `its` using `grep its -n --color=auto -R vignettes` in the vignette `.Rnw` files and removed them where found.

**Comment by joshuaulrich** [comment]
I was taking one last look before merging, and found one more:

```
man/to.period.Rd:115:\sQuote{ts}, \sQuote{its}, and \sQuote{irts}. It is even likely
```

It's ready to merge once that reference in `to.period` is removed.  Thanks again for tackling this!

**Comment by mbeigel** [comment]
And fixed. Thanks for the feedback!

**Comment by joshuaulrich** [comment]
A couple other follow-ups for future reference:
1) It's good practice to create a new branch when you create a PR.  If you use master, and someone doesn't merge your PR verbatim, you will have a mess to clean up in your repo.
2) It's also good practice to wrap the body of your commit message at ~72 characters.

**Comment by mbeigel** [comment]
Thanks for the advice. I noticed a similar issue with your other package, `quantmod`, having references to `its` and will work on that shortly. I'll keep in mind what you've mentioned when I tackle that.

**Pull request merged**
