### PR TITLE
moved col length checks to cover multi.panel = T as well as being num…

### LINKED ISSUE #423: plot.xts doesn't plot more than 8 columns properly on `multi.panel = T`
### Description

when plotting more than 8 columns in multi.panel, the last columns dont display 
this is because plot.xts defaults `col = 1:8`

### Expected behavior

default should handle any number of columns properly,  either recycling the colors after 8, or defaulting `col = 1:ncol(x)`

### Minimal, reproducible example

```r
d <- xts(matrix(1:100, ncol = 10), order.by = Sys.Date() + (1:10))
plot(d, multi.panel = T)
plot(d, multi.panel = T, col = 1:ncol(d))
```

### Session Info

```r
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Denver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xts_0.14.1 zoo_1.8-12

loaded via a namespace (and not attached):
[1] compiler_4.4.0 grid_4.4.0     lattice_0.22-6
```

### PR DESCRIPTION
**Pull request by ethanbsmith**
moved input length checks up in flow to cover both (multi.panel == TRUE) and (is.numeric(multi.panel))
fixes #423

### CODE REVIEW

**Comment by ethanbsmith** [comment]
tbh, im not sure if we even need to check for mlti.panel. is there any harm in just doing this recycling for all scenarios?

**Comment by joshuaulrich** [comment]
Thanks for the PR! I just added a commit that removed some later checks on the length of 'col', 'lty', and 'lwd' so they're only in one place in `plot.xts()` and one place in `chart.lines()`. Can you test this to make sure that didn't break anything? Thanks!

**Comment by ethanbsmith** [comment]
hmm, im getting an error in `addEventLines` now. need to drill into this to isolate the issues

**Comment by joshuaulrich** [comment]
Can you give me an example so I can take a look too?

**Comment by ethanbsmith** [comment]
``` r
x <- as.xts(sample_matrix)
> plot(x, multi.panel = TRUE)
> addEventLines(xts("a", index(x)[10]), pos = 2:3)

```
seems to only be drawing on `pos = 4`
there seems to be a very similar variant of parameter recycling going on at the beginning of this function., but using `times`, not `length,out`

**Comment by joshuaulrich** [comment]
That's a bug, but not related to these changes. It's in the prior version on CRAN (0.14.0).

**Comment by ethanbsmith** [comment]
sry, should be `addEventLines(xts("a", index(x)[10]), on = 2:3)`
thats the error im seeing

**Comment by ethanbsmith** [comment]
working fine. all issues were on my end

**Pull request merged**
