### PR TITLE
Correct time of day subsetting when using hours.

### LINKED ISSUE #326: Time of day subsetting by hour only giving unexpected result
The recent time of day subsetting changes have generated some unexpected results.

```
library(quantstrat)  # get some intraday bar data
.from='2002-10-21'
.to='2002-10-31'
getSymbols.FI(Symbols='GBPUSD',
              dir=system.file('extdata',package='quantstrat'),
              from=.from, to=.to
              , extension = 'rda'
              , use_identifier=NA
)
```

Subsetting by just hour used to work, but now gives incorrect results, and also  seems to still depend on `indexTZ`:
```

head(GBPUSD["T02/T03"])
# Open   High    Low  Close Volume
# 2002-10-22 1.5429 1.5430 1.5429 1.5430      0
# 2002-10-23 1.5464 1.5464 1.5464 1.5464      0
# 2002-10-24 1.5473 1.5473 1.5472 1.5472      0
# 2002-10-25 1.5544 1.5544 1.5544 1.5544      0
# 2002-10-28 1.5474 1.5474 1.5474 1.5474      0
# 2002-10-29 1.5583 1.5583 1.5583 1.5583      0
# Warning message:
#   'indexTZ' is deprecated.
# Use 'tzone' instead.
# See help("Deprecated") and help("xts-deprecated"). 
```

But we do at least get expected results if including the minutes (but still have the `indexTZ` issue)
```
head(GBPUSD["T02:00/T03:00"])
# Open   High    Low  Close Volume
# 2002-10-21 02:00:00 1.5480 1.5480 1.5480 1.5480      0
# 2002-10-21 02:01:00 1.5480 1.5480 1.5480 1.5480      0
# 2002-10-21 02:02:00 1.5479 1.5480 1.5479 1.5480      0
# 2002-10-21 02:03:00 1.5482 1.5482 1.5482 1.5482      0
# 2002-10-21 02:04:00 1.5481 1.5482 1.5481 1.5482      0
# 2002-10-21 02:05:00 1.5481 1.5482 1.5481 1.5482      0
# Warning message:
#   'indexTZ' is deprecated.
# Use 'tzone' instead.
# See help("Deprecated") and help("xts-deprecated"). 

```
Happy to work on a PR to fix this issue if it hasn't been identified yet?

### PR DESCRIPTION
**Pull request by claymoremarshall**
e.g.  subsetting with time of day using hours only, e.g. "T01/T03", does not currently give expected
results, returnong the incorrect rows for the time window.

This requires modifying `.subsetTimeOfDay()`, which did not cover all behaviour previously covered by subsetting which used `.parseISO8601()`.

Careful attention is needed to ensure the second time string (T03 in the above example) covers all bars up to the end of the hour (03:59:59.9999) as was the behaviour previously with `.parseISO8601()`.

An (optional) timeString validation is done to ensure passed in time strings are valid.

Unit tests also updated for time of day subsetting.

Fixes #326

### CODE REVIEW

**Comment by joshuaulrich** [comment]
I only had time to take a quick look, but this looks very thorough!  I will do a more comprehensive review this weekend.

I did notice you added this test: `checkException(x["T0100/T0115"])`. That will break existing code. 

I won't ask you to add comprehensive test coverage for existing functionality before accepting this PR (though I appreciate any tests you do add!). But it's best practice to write and run your unit tests before making any changes, to ensure they produce expected behavior (including errors you intend to fix).  So I would appreciate if you ran your tests against `master` before adding your changes.

**Comment by claymoremarshall** [comment]
Regarding this, do you want to support `x["T0100/T0115"]`?
I made an assumption that users should be forced to do `x["T01:00/T01:15"]` instead, but can modify the patch to permit without colons if desired. Just makes string checking a little more tricky

**Comment by braverock** [comment]
> Regarding this, do you want to support `x["T0100/T0115"]`?
> I made an assumption that users should be forced to do `x["T01:00/T01:15"]` instead, but can modify the patch to permit without colons if desired. Just makes string checking a little more tricky

I would suggest requiring the colon.  The ISO standard, as I recall, expects the colon, and forcing a model of ##:##:##.######## seems to leave the smallest number of ways in qhich this could be misinterpreted.

**Comment by joshuaulrich** [comment]
> I would suggest requiring the colon. The ISO standard, as I recall, expects the colon

I just [looked at the standard](https://en.wikipedia.org/wiki/ISO_8601#Times). The basic format does not use a colon, while the extended format does.  Both are acceptable.

**Review by joshuaulrich — APPROVED** [review]

**Comment by joshuaulrich** [comment]
@claymoremarshall thanks a lot for taking the initiative to fix this bug! Your code and tests were a really good start, and made it a lot easier for me to make updates.

I restored the 'basic format' functionality and made the regex a bit more robust. I also removed the ability to omit zero-padding on everything except hours. That wasn't supported previously, so we're not losing anything, and it makes the xts time-of-day strings conform to the standard (except that the leading zero can be omitted from hours, which isn't in the standard).

**Pull request merged**
