### PR TITLE
Use the updated Travis script with bspm

### PR DESCRIPTION
**Pull request by eddelbuettel**
Please review the [contributing guide](CONTRIBUTING.md) before submitting your pull request. Please pay special attention to the [pull request](CONTRIBUTING.md#want-to-submit-a-pull-request) and [commit message](CONTRIBUTING.md#commit-messages) sections. Thanks for your contribution and interest in the project!

### CODE REVIEW

**Comment by joshuaulrich** [comment]
Looks good.

A couple questions, for my reference in case I make these changes in other packages: (1) is removing the `R_VERSION="4.0"` required? (2) are the quotes necessary for `_R_CHECK_DEPENDS_ONLY_="true"`?

**Comment by eddelbuettel** [comment]
Removng `R_VERSION=4.0` is not required -- but I find it cleaner to do so as that is now the default value.  Quotes for the value is also something I am a little inconsistent about.  I think it works with and without (and the conversion to text is implicit).  You can change either and set whichever other variable you want -- for now only enabling BSPM is important. I may make that a default in a few months.

**Comment by joshuaulrich** [comment]
Thanks for the info. I wasn't concerned about either, which is why I merged. I just wanted to understand the rationale, in case it was important.  Appreciate it!

**Comment by eddelbuettel** [comment]
"With quotes" also happens to look neither in most editors for YAML files such as this--uses a different color.

**Pull request merged**
